name: feature_shared_media_impl
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ^3.0.0

dependencies:
  core_arch:
    path: ../../core_arch
  core_arch_flutter:
    path: ../../core_arch_flutter
  core_tdlib_api:
    path: ../../core_tdlib_api
  dmg_annotation:
    path: ../../dependencies_module_generator/dmg_annotation
  feature_shared_media_api:
    path: ../feature_shared_media_api
  flutter:
    sdk: flutter
  jugger: 3.0.0
  localization_api:
    path: ../../localization_api
  scope_generator_annotation:
    path: ../../scope_generator/scope_generator_annotation

dev_dependencies:
  build_runner: 2.1.7
  dependencies_module_generator:
    path: ../../dependencies_module_generator/generator
  dependency_validator: 3.2.0
  jugger_generator: 3.0.0
  scope_generator:
    path: ../../scope_generator/generator
  tg_lint_rules:
    path: ../../tg_lint_rules

flutter: