name: feature_chat_forum_impl
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ^3.0.0

dependencies:
  chat_navigation_api:
    path: ../../chat_navigation_api
  core_arch:
    path: ../../../../core_arch
  core_arch_flutter:
    path: ../../../../core_arch_flutter
  dmg_annotation:
    path: ../../../../dependencies_module_generator/dmg_annotation
  feature_chat_forum_api:
    path: ../feature_chat_forum_api
  flutter:
    sdk: flutter
  freezed_annotation: 2.1.0
  jugger: 3.0.0
  localization_api:
    path: ../../../../localization_api
  rxdart: 0.27.3
  scope_generator_annotation:
    path: ../../../../scope_generator/scope_generator_annotation
  tile:
    path: ../../../../tile

dev_dependencies:
  build_runner: 2.2.0
  dependencies_module_generator:
    path: ../../../../dependencies_module_generator/generator
  dependency_validator: 3.2.0
  freezed: 2.1.0+1
  jugger_generator: 3.1.0
  scope_generator:
    path: ../../../../scope_generator/generator
  tg_lint_rules:
    path: ../../../../tg_lint_rules
