name: feature_sessions_impl
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ^3.0.0

dependencies:
  core_arch:
    path: ../../core_arch
  core_arch_flutter:
    path: ../../core_arch_flutter
  core_tdlib_api:
    path: ../../core_tdlib_api
  core_ui_jugger:
    path: ../../core_ui_jugger
  coreui:
    path: ../../coreui
  dialog_api:
    path: ../../dialog_api
  dmg_annotation:
    path: ../../dependencies_module_generator/dmg_annotation
  feature_sessions_api:
    path: ../feature_sessions_api
  flutter:
    sdk: flutter
  freezed_annotation: 2.2.0
  jugger: 3.0.0
  localization_api:
    path: ../../localization_api
  rxdart: 0.27.3
  scope_generator_annotation:
    path: ../../scope_generator/scope_generator_annotation
  td_api:
    path: ../../td/td_api
  tile:
    path: ../../tile

dev_dependencies:
  build_runner: 2.3.2
  dependencies_module_generator:
    path: ../../dependencies_module_generator/generator
  dependency_validator: 3.2.0
  freezed: 2.2.1
  jugger_generator: 3.1.1
  scope_generator:
    path: ../../scope_generator/generator
  tg_lint_rules:
    path: ../../tg_lint_rules