name: feature_new_contact_impl
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ^3.0.0

dependencies:
  async: 2.8.2
  async_utils:
    path: ../../../../async_utils
  block_interaction_api:
    path: ../../../../block_interaction_api
  contacts_manager_api:
    path: ../../../contact/contacts_manager/contacts_manager_api
  core_arch:
    path: ../../../../core_arch
  core_arch_flutter:
    path: ../../../../core_arch_flutter
  core_tdlib_api:
    path: ../../../../core_tdlib_api
  core_ui_jugger:
    path: ../../../../core_ui_jugger
  core_utils:
    path: ../../../../core_utils
  coreui:
    path: ../../../../coreui
  dialog_api:
    path: ../../../../dialog_api
  dmg_annotation:
    path: ../../../../dependencies_module_generator/dmg_annotation
  error_transformer_api:
    path: ../../../../error_transformer_api
  feature_file_api:
    path: ../../../../feature/feature_file_api
  feature_new_contact_api:
    path: ../feature_new_contact_api
  flutter:
    sdk: flutter
  freezed_annotation: 1.1.0
  jugger: 2.4.0-dev.1
  localization_api:
    path: ../../../../localization_api
  rxdart: 0.27.3
  scope_generator_annotation:
    path: ../../../../scope_generator/scope_generator_annotation
  shared_models:
    path: ../../../../shared/models
  td_api:
    path: ../../../../td/td_api
  user_info:
    path: ../../../user/user_info

dev_dependencies:
  build_runner: 2.1.7
  dependencies_module_generator:
    path: ../../../../dependencies_module_generator/generator
  dependency_validator: 3.2.0
  freezed: 1.1.1
  jugger_generator: 3.0.0-dev.1
  scope_generator:
    path: ../../../../scope_generator/generator
  tg_lint_rules:
    path: ../../../../tg_lint_rules