name: feature_logout_impl
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ^3.0.0

dependencies:
  auth_manager_api:
    path: ../../component/auth_manager/auth_manager_api
  chat_navigation_api:
    path: ../chat/chat_navigation_api
  core_arch:
    path: ../../core_arch
  core_tdlib_api:
    path: ../../core_tdlib_api
  coreui:
    path: ../../coreui
  dialog_api:
    path: ../../dialog_api
  feature_logout_api:
    path: ../feature_logout_api
  flutter:
    sdk: flutter
  flutter_bloc: 8.0.1
  freezed_annotation: 2.1.0
  localization_api:
    path: ../../localization_api
  provider: 6.0.2

dev_dependencies:
  build_runner: 2.2.0
  dependency_validator: 3.2.0
  freezed: 2.1.0+1
  tg_lint_rules:
    path: ../../tg_lint_rules