name: coreui
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  core_tdlib_api:
    path: ../core_tdlib_api
  core_utils:
    path: ../core_utils
  feature_file_api:
    path: ../feature/feature_file_api
  flutter:
    sdk: flutter
  jugger:
    git:
      url: git@github.com:ivk1800/jugger.dart.git
      path: jugger
      ref: 85d05caacbe81d3a683c1d31a9b27735e512bb93

dev_dependencies:
  tg_lint_rules:
    path: ../tg_lint_rules

flutter:
  assets:
    - assets/icon/