name: td_rich_text_parser
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  rich_text_format:
    path: ../rich_text_format
  td_api:
    path: ../../td/td_api

dev_dependencies:
  dependency_validator: 3.2.0
  test: 1.21.5
  tg_lint_rules:
    path: ../../tg_lint_rules