name: core_arch_flutter
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ^3.0.0

dependencies:
  core_arch:
    path: ../core_arch
  flutter:
    sdk: flutter
  provider: 6.0.2

dev_dependencies:
  tg_lint_rules:
    path: ../tg_lint_rules