name: app
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  app_controller:
    path: ../component/app_controller
  auth_manager_api:
    path: ../component/auth_manager/auth_manager_api
  auth_manager_impl:
    path: ../component/auth_manager/auth_manager_impl
  block_interaction_api:
    path: ../block_interaction_api
  chat_manager_api:
    path: ../feature/chat/chat_manager/chat_manager_api
  chat_manager_impl:
    path: ../feature/chat/chat_manager/chat_manager_impl
  chat_navigation_api:
    path: ../feature/chat/chat_navigation_api
  chat_theme:
    path: ../feature/chat/chat_theme
  contacts_manager_api:
    path: ../feature/contact/contacts_manager/contacts_manager_api
  contacts_manager_impl:
    path: ../feature/contact/contacts_manager/contacts_manager_impl
  core:
    path: ../core
  core_tdlib_api:
    path: ../core_tdlib_api
  core_tdlib_impl:
    path: ../core_tdlib_impl
  core_utils:
    path: ../core_utils
  coreui:
    path: ../coreui
  dialog_api:
    path: ../dialog_api
  dialog_api_flutter:
    path: ../dialog_api_flutter
  error_transformer_api:
    path: ../error_transformer_api
  error_transformer_td:
    path: ../error_transformer_td
  feature_auth_api:
    path: ../feature/feature_auth_api
  feature_auth_impl:
    path: ../feature/feature_auth_impl
  feature_change_bio_api:
    path: ../feature/user/feature_change_bio_api
  feature_change_bio_impl:
      path: ../feature/user/feature_change_bio_impl
  feature_change_username_api:
    path: ../feature/user/feature_change_username_api
  feature_change_username_impl:
    path: ../feature/user/feature_change_username_impl
  feature_chat_administration_api:
    path: ../feature/chat/administration/feature_chat_administration_api
  feature_chat_administration_impl:
    path: ../feature/chat/administration/feature_chat_administration_impl
  feature_chat_api:
    path: ../feature/chat/feature_chat_api
  feature_chat_header_info_api:
    path: ../feature/feature_chat_header_info_api
  feature_chat_header_info_impl:
    path: ../feature/feature_chat_header_info_impl
  feature_chat_impl:
    path: ../feature/chat/feature_chat_impl
  feature_chat_settings_api:
    path: ../feature/feature_chat_settings_api
  feature_chat_settings_impl:
    path: ../feature/feature_chat_settings_impl
  feature_chats_list_api:
    path: ../feature/feature_chats_list_api
  feature_chats_list_impl:
    path: ../feature/feature_chats_list_impl
  feature_contacts_api:
    path: ../feature/contact/contacts/feature_contacts_api
  feature_contacts_impl:
    path: ../feature/contact/contacts/feature_contacts_impl
  feature_country_api:
    path: ../feature/feature_country_api
  feature_country_impl:
    path: ../feature/feature_country_impl
  feature_create_new_chat_api:
    path: ../feature/feature_create_new_chat_api
  feature_create_new_chat_impl:
    path: ../feature/feature_create_new_chat_impl
  feature_data_settings_api:
    path: ../feature/feature_data_settings_api
  feature_data_settings_impl:
    path: ../feature/feature_data_settings_impl
  feature_dev:
    path: ../feature/feature_dev
  feature_file_api:
    path: ../feature/feature_file_api
  feature_file_impl:
    path: ../feature/feature_file_impl
  feature_folders_api:
    path: ../feature/folders/feature_folders_api
  feature_folders_impl:
    path: ../feature/folders/feature_folders_impl
  feature_global_search_api:
    path: ../feature/feature_global_search_api
  feature_global_search_impl:
    path: ../feature/feature_global_search_impl
  feature_logout_api:
    path: ../feature/feature_logout_api
  feature_logout_impl:
    path: ../feature/feature_logout_impl
  feature_main_screen_api:
    path: ../feature/feature_main_screen_api
  feature_main_screen_impl:
    path: ../feature/feature_main_screen_impl
  feature_message_preview_resolver_impl:
    path: ../feature/feature_message_preview_resolver_impl
  feature_new_contact_api:
    path: ../feature/contact/new_contact/feature_new_contact_api
  feature_new_contact_impl:
    path: ../feature/contact/new_contact/feature_new_contact_impl
  feature_notifications_settings_api:
    path: ../feature/feature_notifications_settings_api
  feature_notifications_settings_impl:
    path: ../feature/feature_notifications_settings_impl
  feature_privacy_settings_api:
    path: ../feature/feature_privacy_settings_api
  feature_privacy_settings_impl:
    path: ../feature/feature_privacy_settings_impl
  feature_profile_api:
    path: ../feature/profile/feature_profile_api
  feature_profile_impl:
    path: ../feature/profile/feature_profile_impl
  feature_sessions_api:
    path: ../feature/feature_sessions_api
  feature_sessions_impl:
    path: ../feature/feature_sessions_impl
  feature_settings_api:
    path: ../feature/feature_settings_api
  feature_settings_impl:
    path: ../feature/feature_settings_impl
  feature_settings_search_api:
    path: ../feature/feature_settings_search_api
  feature_settings_search_impl:
    path: ../feature/feature_settings_search_impl
  feature_shared_media_api:
    path: ../feature/feature_shared_media_api
  feature_shared_media_impl:
    path: ../feature/feature_shared_media_impl
  feature_stickers_api:
    path: ../feature/feature_stickers_api
  feature_stickers_impl:
    path: ../feature/feature_stickers_impl
  feature_wallpapers_api:
    path: ../feature/feature_wallpapers_api
  feature_wallpapers_impl:
    path: ../feature/feature_wallpapers_impl
  flutter:
    sdk: flutter
  jugger: 2.2.0
  localization_api:
    path: ../localization_api
  localization_impl:
    path: ../localization_impl
  split_view:
    path: ../split_view
  td_api:
    path: ../td/td_api
  td_client:
    path: ../td_client
  tg_logger_api:
    path: ../tg_logger_api
  tg_logger_impl:
    path: ../tg_logger_impl
  tg_theme:
    path: ../feature/theme/tg_theme
  theme_manager_api:
    path: ../feature/theme/theme_manager_api
  theme_manager_flutter:
    path: ../feature/theme/theme_manager_flutter

dev_dependencies:
  build_runner: 2.1.7
  dependency_validator: 3.2.0
  jugger_generator: 2.4.0
  tg_lint_rules:
    path: ../tg_lint_rules

flutter:
  assets:
    - assets/tdlib/config.txt