name: theme_manager_api
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  freezed_annotation: 2.2.0

dev_dependencies:
  build_runner: 2.3.2
  dependency_validator: 3.2.0
  freezed: 2.2.1
  tg_lint_rules:
    path: ../../../tg_lint_rules