name: td_api
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  tdlib:
    git:
      url: git@github.com:ivk1800/tdlib-dart.git
      ref: 5b8706cc2b1ee2603fd9bf9b8d1591f23d4a81d3

dev_dependencies:
  dependency_validator: 3.2.0
  tg_lint_rules:
    path: ../../tg_lint_rules