name: feature_chats_list_impl
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ^3.0.0

dependencies:
  badges: 2.0.2
  chat_navigation_api:
    path: ../chat/chat_navigation_api
  collection: 1.16.0
  core_arch:
    path: ../../core_arch
  core_arch_flutter:
    path: ../../core_arch_flutter
  core_tdlib_api:
    path: ../../core_tdlib_api
  core_utils:
    path: ../../core_utils
  coreui:
    path: ../../coreui
  dmg_annotation:
    path: ../../dependencies_module_generator/dmg_annotation
  feature_chats_list_api:
    path: ../feature_chats_list_api
  feature_file_api:
    path: ../feature_file_api
  feature_message_preview_resolver:
    path: ../feature_message_preview_resolver
  flutter:
    sdk: flutter
  flutter_svg: 1.0.3
  freezed_annotation: 1.1.0
  jugger: 2.4.0-dev.1
  provider: 6.0.2
  queue:
    path: ../../queue
  rxdart: 0.27.3
  scope_generator_annotation:
    path: ../../scope_generator/scope_generator_annotation
  shared_models:
    path: ../../shared/models
  shimmer: 2.0.0
  td_api:
    path: ../../td/td_api
  tile:
    path: ../../tile

dev_dependencies:
  build_runner: 2.1.7
  dependencies_module_generator:
    path: ../../dependencies_module_generator/generator
  dependency_validator: 3.2.0
  fake:
    path: ../../fake
  freezed: 1.1.1
  jugger_generator: 3.0.0-dev.1
  mockito: 5.1.0
  scope_generator:
    path: ../../scope_generator/generator
  test: 1.20.1
  tg_lint_rules:
    path: ../../tg_lint_rules