name: feature_profile_api
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  profile_navigation_api:
    path: ../profile_navigation_api

dev_dependencies:
  dependency_validator: 3.2.0
  tg_lint_rules:
    path: ../../../tg_lint_rules