name: feature_chat_settings_impl
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ^3.0.0

dependencies:
  core_arch:
    path: ../../core_arch
  core_tdlib_api:
    path: ../../core_tdlib_api
  coreui:
    path: ../../coreui
  feature_chat_settings_api:
    path: ../feature_chat_settings_api
  flutter:
    sdk: flutter
  flutter_bloc: 8.0.1
  freezed_annotation: 2.2.0
  localization_api:
    path: ../../localization_api
  provider: 6.0.2

dev_dependencies:
  build_runner: 2.3.2
  dependency_validator: 3.2.0
  freezed: 2.2.1
  tg_lint_rules:
    path: ../../tg_lint_rules