name: feature_country_impl
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ^3.0.0

dependencies:
  bloc: 8.0.2
  collection: 1.16.0
  feature_country_api:
    path: ../feature_country_api
  flutter:
    sdk: flutter
  flutter_bloc: 8.0.1
  freezed_annotation: 2.2.0
  localization_api:
    path: ../../localization_api
  provider: 6.0.2

dev_dependencies:
  build_runner: 2.3.2
  dependency_validator: 3.2.0
  freezed: 2.2.1
  tg_lint_rules:
    path: ../../tg_lint_rules

flutter:
  assets:
    - assets/countries.txt