name: chat_actions_panel
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ^3.0.0

dependencies:
  async: 2.8.2
  async_utils:
    path: ../../../async_utils
  chat_manager_api:
    path: ../chat_manager/chat_manager_api
  core_arch:
    path: ../../../core_arch
  core_arch_flutter:
    path: ../../../core_arch_flutter
  core_tdlib_api:
    path: ../../../core_tdlib_api
  dialog_api:
    path: ../../../dialog_api
  error_transformer_api:
    path: ../../../error_transformer_api
  flutter:
    sdk: flutter
  freezed_annotation: 1.1.0
  jugger: 2.4.0-dev.1
  localization_api:
    path: ../../../localization_api
  rxdart: 0.27.3
  td_api:
    path: ../../../td/td_api
  tuple: 2.0.0

dev_dependencies:
  build_runner: 2.1.7
  dependency_validator: 3.2.0
  freezed: 1.1.1
  jugger_generator: 3.0.0-dev.1
  tg_lint_rules:
    path: ../../../tg_lint_rules